### ISSUE TITLE
rair-node stopped with Error "Error: Invalid signature v value "

### ISSUE THREAD

**Issue by sarora180673** [rairprotocol/rair-dapp#114]
https://hotdrops.live/  was working fine. But it was observed that after 1-2 days of running, rair-node stopped with error message:

6:13:01 PM web.1 |  /usr/src/rairnode/node_modules/@ethereumjs/util/dist/signature.js:46
6:13:01 PM web.1 |          throw new Error('Invalid signature v value');
6:13:01 PM web.1 |                ^
6:13:01 PM web.1 |  Error: Invalid signature v value
6:13:01 PM web.1 |      at ecrecover (/usr/src/rairnode/node_modules/@ethereumjs/util/dist/signature.js:46:15)
6:13:01 PM web.1 |      at recoverPublicKey (/usr/src/rairnode/node_modules/@metamask/eth-sig-util/dist/utils.js:79:33)
6:13:01 PM web.1 |      at recoverTypedSignature (/usr/src/rairnode/node_modules/@metamask/eth-sig-util/dist/sign-typed-data.js:398:52)
6:13:01 PM web.1 |      at recoverUserFromSignature (/usr/src/rairnode/bin/integrations/ethers/web3Signature.js:56:27)
6:13:01 PM web.1 |      at checkChallenge (/usr/src/rairnode/bin/integrations/ethers/web3Signature.js:66:27)
6:13:01 PM web.1 |      at validateChallenge (/usr/src/rairnode/bin/integrations/ethers/web3Signature.js:108:29)
6:13:01 PM web.1 |      at validateChallengeV2 (/usr/src/rairnode/bin/integrations/ethers/web3Signature.js:172:26)
6:13:01 PM web.1 |      at Layer.handle [as handle_request] (/usr/src/rairnode/node_modules/express/lib/router/layer.js:95:5)
6:13:01 PM web.1 |      at next (/usr/src/rairnode/node_modules/express/lib/router/route.js:149:13)
6:13:01 PM web.1 |      at /usr/src/rairnode/bin/middleware/validation.js:17:14
6:13:01 PM web.1 |  Node.js v20.15.0
6:13:01 PM web.1 Exited with exit code SIGINT

**Comment by sarora180673** [comment]
Verified by login with Metamask and SmartAccount
